Repository Pda4thMiniProject4th/shitdown-be, pull requests merged in 2024-05, with the labels that each got.

#2 feat: BE 초기 세팅
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  app.js
  bin/www
  package-lock.json
  package.json
  public/stylesheets/style.css
  routes/index.js
  routes/users.js
  views/error.ejs
  views/index.ejs
Labels: :broom: chore, :runner: init

#4 chore: cicd.yml - 백엔드 CICD 배포
  .github/workflows/cicd.yml
Labels: :broom: chore, :runner: init

#8 Feat/dbschema: 더미 데이터 생성 완료
  app.js
  models/Seats.js
  models/Users.js
  routes/api/seats.js
  routes/api/users.js
Labels: 💡 Feature

#13 feat: 현좌석배치 유저네임 리스트 호출 api 개발
  routes/api/seats.js
  routes/index.js
Labels: 💡 Feature

#15 feat : 자리배치 관리자 페이지 api 개발, fix : Seats, Notice 스키마 변경
  app.js
  models/Notices.js
  models/Seats.js
  package-lock.json
  package.json
  routes/api/notice.js
  routes/api/seats.js
  services/seats.js
  valid/Valid.js
Labels: :broom: chore, :hammer_and_wrench: fix, 💡 Feature

#17 feat: notice.js - 메인페이지 공지 API 개발 완료
  package-lock.json
  package.json
  routes/api/notice.js
Labels: 💡 Feature

#19 feat: 현재좌석api 수정
  routes/api/seats.js
Labels: 💡 Feature

#21 feat: 좌석 선택 및 확정 api 및 users모델 reason 속성 추가
  app.js
  models/Users.js
  routes/api/seats.js
  routes/api/users.js
Labels: 💡 Feature

#23 feat: 마이페이지 API 개발 완료
  app.js
  routes/api/mypage.js
Labels: 💡 Feature

#25 feat: api 정리
  routes/api/seats.js
  routes/api/users.js
Labels: 💡 Feature

#32 feat: users.js - 실시간 좌석 API 개발 완료, fix: seats.js - 요구사항 변경으로 따른 자리 배치 로직 수정
  routes/api/users.js
  services/seats.js
Labels: :hammer_and_wrench: fix, 💡 Feature

#31 fix: seats/live api 수정(seat-option:-2반영)
  routes/api/seats.js
Labels: :hammer_and_wrench: fix

#34 fix: seats/current/:orders api 수정
  package-lock.json
  routes/api/seats.js
Labels: :hammer_and_wrench: fix

#36 fix: Seat 스키마의 seat에 username 추가 및 valid 로직 수정
  routes/api/seats.js
  services/seats.js
  valid/Valid.js
Labels: :hammer_and_wrench: fix

#38 refactor: current/:orders api 수정
  routes/api/seats.js
Labels: :recycle: refactor

#40 feat: 자리 배치 로직 수정
  services/seats.js
Labels: :hammer_and_wrench: fix

#41 fix: seat.js - /:orders 좌석 매핑 위한 API 수정
  routes/api/seats.js
Labels: :hammer_and_wrench: fix

#42 Feat: 유저의 정보 업데이트
  app.js
  models/Users.js
  package-lock.json
  package.json
  routes/api/users.js
  routes/auth.js
  routes/users.js
Labels: 💡 Feature

#43 feat: 유저 정보 업데이트 기능 #26
  app.js
  routes/api/users.js
  routes/auth.js
Labels: 💡 Feature

#44 feat: 중간점검 merge
  app.js
  routes/api/mypage.js
  routes/api/seats.js
  routes/api/users.js
Labels: 💡 Feature

#45 feat: userId와 admin 리턴
  routes/api/users.js
  routes/auth.js
Labels: 💡 Feature

#46 fix: cicd.yml - EC2 변경에 의한 cicd 파일 변경
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#47 fix: cicd.yml - 에러 수정
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#50 ADD KAKAOTOKEN
  .github/workflows/cicd.yml
Labels: 💡 Feature

#49 feat: jwt토큰 생성과 토큰 유효성 검사 기능
  app.js
  routes/api/creatToken.js
  routes/api/verifyToken.js
Labels: 💡 Feature

#52 feat: id에 따른 기수 정보 API 개발 완료
  routes/api/users.js
Labels: 💡 Feature

#53 fix: id에 따른 기수 정보 API에 프로필 정보도 추가 완료
  routes/api/users.js
Labels: :hammer_and_wrench: fix

#55 feat: 회원 정보 업데이트 API 추가
  routes/api/seats.js
  routes/api/users.js
  services/seats.js
Labels: :hammer_and_wrench: fix, 💡 Feature

#56 feat: logout 기능 추가
  app.js
  routes/api/users.js
  routes/api/verifyToken.js
  routes/auth.js
Labels: 💡 Feature

#57 fix: seat.js - 진짜진짜 마지막 로직 수정
  services/seats.js
Labels: :hammer_and_wrench: fix

#58 fix: 로그아웃 시 재로그인 수정 #26
  routes/auth.js
Labels: 💡 Feature

#59 ADD LOGOUT_URI
  .github/workflows/cicd.yml
Labels: 💡 Feature

#61 feat: 슬랙과 연동
  .github/workflows/cicd.yml
  app.js
  package.json
  routes/api/users.js
Labels: 💡 Feature

#62 fix: cicd.yml - cicd 로직 개선
  .github/workflows/cicd.yml
Labels: :hammer_and_wrench: fix

#63 feat: users.js - 유저 정보 업데이트 api 추가
  routes/api/users.js
Labels: 💡 Feature
